basePath: /
definitions:
  data.AuthLoginReq:
    properties:
      email:
        type: string
      password:
        maxLength: 255
        type: string
    required:
    - email
    - password
    type: object
  data.AuthRegisterReq:
    properties:
      email:
        maxLength: 255
        type: string
      name:
        maxLength: 255
        minLength: 1
        type: string
      password:
        maxLength: 255
        type: string
    required:
    - email
    - name
    - password
    type: object
  data.AuthUserInfo:
    properties:
      email:
        type: string
      lastPing:
        type: integer
      role:
        type: string
      userID:
        type: integer
      userName:
        type: string
    type: object
  data.OrderCancelReq:
    properties:
      reason:
        maxLength: 255
        type: string
    required:
    - reason
    type: object
  data.OrderCancelRes:
    properties:
      modifiedBy:
        type: string
      modifiedDate:
        type: string
    type: object
  data.OrderCompletedRes:
    properties:
      modifiedBy:
        type: string
      modifiedDate:
        type: string
    type: object
  data.OrderConfirmRes:
    properties:
      modifiedBy:
        type: string
      modifiedDate:
        type: string
    type: object
  data.OrderCreateReq:
    properties:
      id:
        type: integer
      orderDetails:
        items:
          $ref: '#/definitions/data.OrderDetail'
        maxItems: 10
        type: array
    required:
    - orderDetails
    type: object
  data.OrderCreateRes:
    properties:
      createBy:
        type: string
      createCount:
        type: integer
      createdDate:
        type: string
      createdID:
        type: integer
      deleteCount:
        type: integer
      updateCount:
        type: integer
    type: object
  data.OrderDeleteRes:
    properties:
      deletedBy:
        type: string
      deletedCount:
        type: integer
      deletedDate:
        type: string
    type: object
  data.OrderDetail:
    properties:
      productID:
        type: integer
      quantity:
        type: integer
    required:
    - productID
    - quantity
    type: object
  data.OrderDetailResult:
    properties:
      description:
        type: string
      id:
        type: integer
      price:
        type: number
      proudctName:
        type: string
      quantity:
        type: integer
      subtotal:
        type: number
    type: object
  data.OrderGetHistoryReq:
    properties:
      page:
        example: 1
        minimum: 1
        type: integer
      perPage:
        example: 10
        minimum: 1
        type: integer
      sortBy:
        properties:
          field:
            example: modifiedDate
            type: string
          mode:
            example: desc
            type: string
        type: object
      status:
        example: ""
        type: string
      userID:
        example: 0
        type: integer
    type: object
  data.OrderGetHistoryRes:
    properties:
      page:
        type: integer
      perPage:
        type: integer
      results:
        items:
          $ref: '#/definitions/data.OrderGetHistoryResult'
        type: array
      totalPages:
        type: integer
      totalResults:
        type: integer
    type: object
  data.OrderGetHistoryResult:
    properties:
      id:
        type: integer
      modifiedDate:
        type: string
      orderDetails:
        items:
          $ref: '#/definitions/data.OrderDetailResult'
        type: array
      reason:
        type: string
      status:
        type: string
      total:
        type: number
      userID:
        type: integer
    type: object
  data.OrderShippingRes:
    properties:
      modifiedBy:
        type: string
      modifiedDate:
        type: string
    type: object
  data.ProductGetListReq:
    properties:
      page:
        example: 1
        minimum: 1
        type: integer
      perPage:
        example: 10
        minimum: 1
        type: integer
      searchText:
        example: ""
        maxLength: 255
        type: string
      sortBy:
        properties:
          field:
            example: id
            type: string
          mode:
            example: asc
            type: string
        type: object
    type: object
  data.ProductGetListRes:
    properties:
      page:
        type: integer
      perPage:
        type: integer
      results:
        items:
          $ref: '#/definitions/data.ProductGetListResult'
        type: array
      totalPages:
        type: integer
      totalResults:
        type: integer
    type: object
  data.ProductGetListResult:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact: {}
  description: This is a sample server API.
  title: APP Ecommerce API
  version: "1.0"
paths:
  /api/admin/order/history:
    post:
      consumes:
      - application/json
      description: admin order get history
      operationId: OrderGetHistoryAdmin
      parameters:
      - description: request body
        in: body
        name: OrderGetHistoryReq
        required: true
        schema:
          $ref: '#/definitions/data.OrderGetHistoryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderGetHistoryRes'
      security:
      - ApiKeyAuth: []
      summary: admin order get history
      tags:
      - order
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: auth login
      operationId: AuthLogin
      parameters:
      - description: request body
        in: body
        name: AuthLoginReq
        required: true
        schema:
          $ref: '#/definitions/data.AuthLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: auth login
      tags:
      - auth
  /api/auth/logout:
    get:
      consumes:
      - application/json
      description: auth logout
      operationId: AuthLogout
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: auth logout
      tags:
      - auth
  /api/auth/refresh:
    get:
      consumes:
      - application/json
      description: auth refresh
      operationId: AuthRefresh
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: auth refresh
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: auth register
      operationId: AuthRegister
      parameters:
      - description: request body
        in: body
        name: AuthRegisterReq
        required: true
        schema:
          $ref: '#/definitions/data.AuthRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: auth register
      tags:
      - auth
  /api/auth/user-info:
    get:
      consumes:
      - application/json
      description: auth user info
      operationId: AuthUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.AuthUserInfo'
      security:
      - ApiKeyAuth: []
      summary: auth user info
      tags:
      - auth
  /api/order/{id}:
    delete:
      consumes:
      - application/json
      description: orderdelete
      operationId: OrderDelete
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderDeleteRes'
      security:
      - ApiKeyAuth: []
      summary: order delete
      tags:
      - order
  /api/order/cancel/{id}:
    put:
      consumes:
      - application/json
      description: orderCancel
      operationId: OrderCancel
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: OrderCancelReq
        required: true
        schema:
          $ref: '#/definitions/data.OrderCancelReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderCancelRes'
      security:
      - ApiKeyAuth: []
      summary: order Cancel
      tags:
      - order
  /api/order/completed/{id}:
    put:
      consumes:
      - application/json
      description: orderCompleted
      operationId: OrderCompleted
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderCompletedRes'
      security:
      - ApiKeyAuth: []
      summary: order Completed
      tags:
      - order
  /api/order/confirm/{id}:
    put:
      consumes:
      - application/json
      description: orderConfirm
      operationId: OrderConfirm
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderConfirmRes'
      security:
      - ApiKeyAuth: []
      summary: order confirm
      tags:
      - order
  /api/order/create:
    post:
      consumes:
      - application/json
      description: order create
      operationId: OrderCreate
      parameters:
      - description: request body
        in: body
        name: OrderCreateReq
        required: true
        schema:
          $ref: '#/definitions/data.OrderCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderCreateRes'
      security:
      - ApiKeyAuth: []
      summary: order create
      tags:
      - order
  /api/order/history:
    post:
      consumes:
      - application/json
      description: order get history
      operationId: OrderGetHistory
      parameters:
      - description: request body
        in: body
        name: OrderGetHistoryReq
        required: true
        schema:
          $ref: '#/definitions/data.OrderGetHistoryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderGetHistoryRes'
      security:
      - ApiKeyAuth: []
      summary: order get history
      tags:
      - order
  /api/order/shipping/{id}:
    put:
      consumes:
      - application/json
      description: orderShipping
      operationId: OrderShipping
      parameters:
      - description: order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.OrderShippingRes'
      security:
      - ApiKeyAuth: []
      summary: order Shipping
      tags:
      - order
  /api/products:
    post:
      consumes:
      - application/json
      description: product get list
      operationId: ProductGetList
      parameters:
      - description: request body
        in: body
        name: ProductGetListReq
        required: true
        schema:
          $ref: '#/definitions/data.ProductGetListReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.ProductGetListRes'
      security:
      - ApiKeyAuth: []
      summary: product get list
      tags:
      - product
  /api/sse:
    get:
      consumes:
      - application/json
      description: SSE Event
      produces:
      - text/event-stream
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: SSE Event
      tags:
      - SSE
  /api/todo/ping:
    get:
      consumes:
      - application/json
      description: todo ping
      operationId: TodoPing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: todo ping
      tags:
      - todo
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
